spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.sqlite.JDBC
#    url: "jdbc:sqlite:/app/logs/tg_archive.db"
    url: "jdbc:sqlite:D:\\app.db"
  ai:
    openai:
      api-key: "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"
  config:
    import: bot-config.yml

openai:
  api-key: "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"

# JVM优化参数（在启动脚本中添加）：
# -Xmx1g -Xms512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200

# 日志级别配置
logging:
  level:
    root: INFO
    com.bot.aabot.service: info # 将日志级别设置为DEBUG可以看到更多处理细节

#  docker run -d \
#  -v /home/ec2-user/data/message_logs:/app/logs \
#  --name TgBot \
#  -it\
#  tg-bot:1