spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.sqlite.JDBC
    url: "jdbc:sqlite:/app/logs/tg_archive.db"
  ai:
    openai:
      api-key: "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"
      chat:
        options:
          model: gpt-4o
          temperature: 0.7
      embedding:
        options:
          model: text-embedding-3-large
    vectorstore:
      qdrant:
        host: "69ce39b0-957e-4ad5-a0c1-54fa15119fc1.europe-west3-0.gcp.cloud.qdrant.io"
        port: 6334
        api-key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.o9gE62G9RdiJagrZCmrOaY7HzyRkDr-dwHC-W3adGWI"
        collection-name: "test"
        use-tls: true

# 日志级别配置
logging:
  level:
    root: INFO
    com.bot.aabot.service: INFO
    com.bot.aabot.utils: INFO
  file:
    path: /app/logs/tgLog
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 5GB
  cleanup:
    days: 30
    enabled: true
