spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.sqlite.JDBC
#    url: "jdbc:sqlite:/app/logs/tg_archive.db"
    url: "jdbc:sqlite:D:\\app.db"
  ai:
    openai:
      api-key: "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"

openai:
  api-key: "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"

bot:
  oneOrEveryday: one # one or everyday ,Log storage: one file per day or everyday
  createId: 7744901692
  message:
    conversation_timeout: 20 #Maximum time a single session can exist in minutes
    max_context: 20 #Maximum maintainable context length for a single user
  knowledge:
    directory-path: "D:\\knowledge" # 知识库文件夹路径
    file-types: .md,.txt # 支持的文件类型，逗号分隔
    recursive: true # 是否递归搜索子文件夹
    update-interval: 60 # 知识库更新频率（分钟）
    chunk-size: 800 # 默认文本块大小（字符数）
    chunk-overlap: 150 # 默认文本块重叠大小（字符数）
    top-k: 3 # 相似度检索结果数量
    similarity-threshold: 0.7 # 相似度阈值
    embedding-model: "text-embedding-3-small" # OpenAI嵌入模型名称

# JVM优化参数（在启动脚本中添加）：
# -Xmx1g -Xms512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200

# 日志级别配置
logging:
  level:
    root: INFO
    com.bot.aabot.service: INFO # 将日志级别设置为DEBUG可以看到更多处理细节

#  docker run -d \
#  -v /home/ec2-user/data/message_logs:/app/logs \
#  --name TgBot \
#  -it\
#  tg-bot:1