bot:
  oneOrEveryday: one # one or everyday ,Log storage: one file per day or everyday
  createId: 7744901692
  message:
    conversation_timeout: 20 #Maximum time a single session can exist in minutes
    max_context: 20 #Maximum maintainable context length for a single user
  knowledge:
    directory-path: "D:\\knowledge" # 知识库文件夹路径
    file-types: .md,.txt # 支持的文件类型，逗号分隔
    recursive: true # 是否递归搜索子文件夹
    update-interval: 60 # 知识库更新频率（分钟）
    chunk-size: 800 # 默认文本块大小（字符数）
    chunk-overlap: 150 # 默认文本块重叠大小（字符数）
    top-k: 3 # 相似度检索结果数量
    similarity-threshold: 0.7 # 相似度阈值
    embedding-model: "text-embedding-3-small" # OpenAI嵌入模型名称 