bot:
#  forbidUrl : "D:\\forbid.txt"
  forbidUrl : "/app/logs/txt/forbid.txt"
  oneOrEveryday: one # one or everyday ,Log storage: one file per day or everyday
  createId: 7744901692
  aiInteraction: true # 是否开启AI互动功能（活动提醒和回答用户问题），默认关闭
  message:
    conversation_timeout: 60 #Maximum time a single session can exist in minutes
    max_context: 20 #Maximum maintainable context length for a single user
  knowledge:
    # 文件加载相关配置（仅在use-qdrant=false时使用）

    file-types: .md,.txt # 支持的文件类型，逗号分隔
    recursive: true # 是否递归搜索子文件夹
    update-interval: 60 # 知识库更新频率（分钟）
    
    # 文本分块相关配置
    chunk-size: 800 # 默认文本块大小（字符数）
    chunk-overlap: 150 # 默认文本块重叠大小（字符数）
    
    # 向量检索相关配置
    top-k: 4 # 相似度检索结果数量
    similarity-threshold: 0.8 # 相似度阈值
#    embedding-model: "text-embetext-embedding-ada-002dding-3-small" # OpenAI嵌入模型名称
    embedding-model: "text-embedding-ada-002" # OpenAI嵌入模型名称

    vector-size: 1536 # 向量维度（text-embedding-3-small模型为1536维）
    
    # Qdrant配置
    use-qdrant: true # 是否使用Qdrant向量数据库
    qdrant:
      url: "https://69ce39b0-957e-4ad5-a0c1-54fa15119fc1.europe-west3-0.gcp.cloud.qdrant.io" # Qdrant Cloud端点
      api-key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.o9gE62G9RdiJagrZCmrOaY7HzyRkDr-dwHC-W3adGWI" # Qdrant API密钥
      collection-name: "test" # Qdrant集合名称
  name: "naseele_bot"